#!/bin/bash
# 
# Deb package postinst script for API Server
#
############ STANDART USER, PASS, BD NAME FOR HISTORY SERVICE ############
user="my_user" #"crane_data_server"
pass="00d0-25e4-*&s2-ccds"
db="crane_data_server"
#
############ INITIAL SQL SCRIPTS ############
echo ""
echo "Creating Hystory database user '$user'..."
source "./sql/create_user.sql"
echo $sql | sudo -i -u postgres psql --echo-errors
#
echo ""
echo "Creating Hystory database '$db'..."
source "./sql/create_db.sql"
echo $sql | sudo -i -u postgres psql --echo-errors
#
echo ""
echo "Creating 'tags' table..."
source "./sql/create_tags.sql"
echo $sql | sudo -i -u postgres psql --echo-errors
#
echo ""
echo "Creating 'event' table..."
source "./sql/create_event.sql"
echo $sql | sudo -i -u postgres psql --echo-errors
#
echo ""
echo "Creating 'event_view' view..."
source "./sql/create_event_view.sql"
echo $sql | sudo -i -u postgres psql --echo-errors
#
echo ""
echo "Creating 'event_view' view..."
source "./sql/create_event_view.sql"
echo $sql | sudo -i -u postgres psql --echo-errors
