#!/bin/bash
# 
# Deb package prerem script for API Server
#
# echo ""
# name="api-server"
# if [[ $(systemctl list-units --all -t service --full --no-legend "$name.service" | sed 's/^\s*//g' | cut -f1 -d' ') == $name.service ]]; then
#     if systemctl is-active --quiet "$name.service" ; then
#         echo "Stopping $name service..."
#         systemctl stop api-server
#     fi    
#     if systemctl is-enabled --quiet "$name.service" ; then
#         echo "Disabling $name service..."
#         systemctl disable api-server
#     fi    
# fi
RED='\033[0;31m'
BLUE='\033[0;34m'
GRAY='\033[1;30m'
NC='\033[0m' # No Color
echo -e ""
echo -e "${RED}All historian data stored in the ${NC}"
echo -e "${RED}database will be permanently removed... ${NC}"
echo -e ""
read -p "Are you sure (yes/no) ? " -n 1 -r
if [[ $REPLY =~ ^[Yy]$ ]]; then
    # do dangerous stuff
fi
echo -e ""
echo -e "PRE RM called with: \ntarg1: $1\ntarg2: $2\ntarg3: $3\ntarg4: $4" 
