read -r -d '' sql << EOF
GRANT CONNECT ON DATABASE $db TO $user;
\c $db
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO $user;
GRANT SELECT, USAGE ON ALL SEQUENCES IN SCHEMA public TO $user;
EOF
